# Generated by Django 5.2.6 on 2025-09-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pontos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sobrevivente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('infectado', models.BooleanField(default=False)),
                ('reports', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sobrevivente.inventario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sobrevivente.item')),
            ],
            options={
                'unique_together': {('item', 'inventario')},
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='itens',
            field=models.ManyToManyField(through='sobrevivente.ItemInventario', to='sobrevivente.item'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='sobrevivente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sobrevivente.sobrevivente'),
        ),
        migrations.CreateModel(
            name='DenunciaInfeccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recebidas', to='sobrevivente.sobrevivente')),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_feitas', to='sobrevivente.sobrevivente')),
            ],
            options={
                'unique_together': {('denunciante', 'denunciado')},
            },
        ),
    ]
