# Generated by Django 5.2.6 on 2025-09-11 22:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobreviventes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Sobrevivente')),
                ('idade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Idade')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude da Localização')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude da Localização')),
                ('infectado', models.BooleanField(default=False, verbose_name='Está Infectado?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Sobrevivente',
                'verbose_name_plural': 'Sobreviventes',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ReporteInfeccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Data do Reporte')),
                ('sobrevivente_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recebidos', to='Sobrevivente.sobreviventes', verbose_name='Sobrevivente Reportado')),
                ('sobrevivente_reportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_feitos', to='Sobrevivente.sobreviventes', verbose_name='Sobrevivente que Reportou')),
            ],
            options={
                'verbose_name': 'Reporte de Infecção',
                'verbose_name_plural': 'Reportes de Infecção',
                'unique_together': {('sobrevivente_reportado', 'sobrevivente_reportador')},
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('agua', 'Água'), ('comida', 'Comida'), ('medicamento', 'Medicamento'), ('municao', 'Munição')], max_length=20, verbose_name='Tipo do Item')),
                ('quantidade', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('sobrevivente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='Sobrevivente.sobreviventes', verbose_name='Sobrevivente')),
            ],
            options={
                'verbose_name': 'Item do Inventário',
                'verbose_name_plural': 'Itens do Inventário',
                'unique_together': {('sobrevivente', 'tipo_item')},
            },
        ),
    ]
